name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.5]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python setup.py test
        env:
          TEST_CLIENT_ID : ${{ secrets.TEST_CLIENT_ID }}
          TEST_CLIENT_SECRET : ${{ secrets.TEST_CLIENT_SECRET }}
      - run: pip install twine wheel
      - run: python setup.py sdist bdist_wheel
      - run: python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
