name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, rc]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - run: python --version
      - run: pip install -r requirements.txt
        if: matrix.python-version != '2.7'
      - run: |
          pip install pylint
          curl https://raw.githubusercontent.com/ripe-tech/pylint-config/master/pylintrc --output pylintrc
          PYTHONPATH=src pylint src/un1qnx
        if: matrix.python-version != '2.7' && matrix.python-version != '3.5'
      - run: |
          pip install black
          black . --check --config ./pyproject.toml
        if: matrix.python-version != '2.7' && matrix.python-version != '3.5'
      - run: python setup.py test
        env:
          TEST_CLIENT_ID : ${{ secrets.TEST_CLIENT_ID }}
          TEST_CLIENT_SECRET : ${{ secrets.TEST_CLIENT_SECRET }}
      - run: |
          pip install coveralls
          coverage run --source=un1qnx --omit="src/un1qnx/test/*" setup.py test
          coveralls
        env:
          TEST_CLIENT_ID : ${{ secrets.TEST_CLIENT_ID }}
          TEST_CLIENT_SECRET : ${{ secrets.TEST_CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
